"""init schema

Revision ID: 6d8d8856610c
Revises: 
Create Date: 2025-05-26 10:42:25.641988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d8d8856610c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotkey_worker",
        sa.Column("worker", sa.String(), nullable=False),
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("signature", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("worker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hotkey_worker")
    # ### end Alembic commands ###
